name: Build and Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Install ğŸ”§
        run: |
          yarn install --frozen-lockfile
      
      - name: Build Contract ğŸ”§
        run: |
          yarn build:contract

      - name: Upload Wasm
        id: upload
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://template-test.free.beeceptor.com/deploy_wasm'
          method: 'POST'
          data: '{"repo_full_name": "${{ github.repository }}", "repo_owner": "${{ github.repository_owner }}"}'
          customHeaders: '{"X-GITHUB-TOKEN": "${{ secrets.GITHUB_TOKEN }}"}'
          files: '{"file":"contract/target/wasm32-unknown-unknown/release/deps/hello_near.wasm"}'
            
      - name: Build Frontend ğŸ”§
        run: |
          yarn build:web
        env:
          CONTRACT_NAME: ${{ fromJson(steps.upload.outputs.response).template_project.near_account_id }}

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          folder: frontend/dist
      
      - name: Update frontend url
        id: update-frontend-url
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://template-test.free.beeceptor.com/set_deploy_frontend_url'
          method: 'PATCH'
          data: '{"frontend_deploy_url": "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}", "deploy_id": "${{ fromJson(steps.upload.outputs.response).template_project.id }}"}'
          customHeaders: '{"X-GITHUB-TOKEN": "${{ secrets.GITHUB_TOKEN }}"}'